apiVersion: apps/v1
kind: Deployment
metadata:
  name: nblotti-brasidas
  labels:
    app: nblotti_brasidas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nblotti_brasidas
  template:
    metadata:
      labels:
        app: nblotti_brasidas
    spec:
      containers:
        - name: nblotti
          image: nblotti/brasidas:v0.0.47
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 6
            periodSeconds: 3600
      imagePullSecrets:
        - name: regcred
