apiVersion: apps/v1
kind: Deployment
metadata:
  name: nblotti-brasidas
  labels:
    app: nblotti_brasidas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nblotti_brasidas
  template:
    metadata:
      labels:
        app: nblotti_brasidas
    spec:
      containers:
        - name: nblotti
          image: nblotti/brasidas:v0.0.44
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            failureThreshold: 30
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred
