package ch.nblotti.brasidas.index.loader;

public enum INDEX_LOADER_STATES {
  READY,
  WAITING_EVENT,
  GET_DATES,
  LOAD_INDEX,
  CLEANUP_INDEX_COMPOSITION,
  LOAD_INDEX_COMPOSITION,
  ERROR_STATE,
  ERROR,
  DONE;

}
